"""Every weed-control decision RIM offers, with what it does and what it costs.

``Calcs`` rows 55-97 and 105-147 are the same list of options twice: once for
what each does to ryegrass, once for what it costs, paired at ``r + 50``. Both
are indexed by crop, because both depend on the crop -- Topik is a
grass-selective cereal herbicide, so it takes 90% of the ryegrass in wheat and
nothing at all in canola, and Glyphosate costs $26/ha in a crop and $22/ha in a
pasture.

This module is the one place that knows which rows belong to which decision on
``2.Strategy``. Both tables are already generated by ``tools/extract_params.py``
into ``data/calcs_survival_table.json`` and ``data/calcs_cost_table.json``;
nothing here is typed.

    knockdown        rows 55-57    2.Strategy row 7
    pre_emergent     rows 58-62    2.Strategy row 8
    post_emergent_1  rows 71-75    2.Strategy row 11
    post_emergent_2  rows 71-75    2.Strategy row 12
    post_emergent_3  rows 71-75    2.Strategy row 13
    spring_option    rows 78-84    2.Strategy row 15
    spring_swathe    rows 87-88    2.Strategy row 16
    spring_others    rows 85-86    2.Strategy row 17
    harvest_option   rows 89-94    2.Strategy row 18
    harvest_others   rows 95-97    2.Strategy row 19

**Names are readable; the workbook's are kept as aliases.** A spreadsheet
abbreviates because a cell is narrow -- "B.all", "Sil.+Spray", "Triflur+Tria" --
and there is no reason to inflict that on a web page. Each row carries a display
name, the workbook label it came from, and every name earlier versions of this
app used. :func:`find` accepts any of them, so renaming a display name can never
strand a saved plan; that is what the alias list is for.

**A zero control is a statement, not a gap.** Where the survival table holds 0
for a crop the option does nothing there, and the workbook means it.
``utils/applicability.py`` reads that and stops offering the option, rather than
charging for something inert.

**The cost table's columns are not in a fixed order.** Rows carry one of two
signatures, ``NOPQRST`` or ``NOPQRTS``, differing in where Clover and Cadiz sit.
The generated file records each row's own signature and has already resolved it
into ``cost_by_crop_code``, so nothing downstream has to know. See
``tools/extract_params.py``.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

_DATA = Path(__file__).resolve().parents[1] / "data"
SURVIVAL_PATH = _DATA / "calcs_survival_table.json"
COST_PATH = _DATA / "calcs_cost_table.json"

# The workbook prices an option's cost row 50 below its control row.
COST_ROW_OFFSET = 50

# What "this decision was not taken" reads as in a strategy row. Harvest is the
# exception: the paddock is always harvested, just without seed control.
NONE = "None"
STANDARD_HARVEST = "Standard"

# 2.Strategy decision -> the Calcs rows it can hold, in the workbook's order.
FIELD_ROWS: dict[str, tuple[int, ...]] = {
    "knockdown": (55, 56, 57),
    "pre_emergent": (58, 59, 60, 61, 62),
    "post_emergent_1": (71, 72, 73, 74, 75),
    "post_emergent_2": (71, 72, 73, 74, 75),
    "post_emergent_3": (71, 72, 73, 74, 75),
    # 2.Strategy D91:D96 order: Green M., Brown M, Mow+Spray, Sil.+Spray,
    # Hay+Spray, Topping.
    "spring_option": (82, 78, 81, 84, 83, 79),
    "spring_swathe": (87, 88),
    "spring_others": (85, 86),
    # D108:D112 order: Cart+B., Narr+B., HSD, Tram., BDS+E. Row 93 is the
    # workbook's spare slot and is not offered.
    "harvest_option": (89, 90, 91, 92, 94),
    "harvest_others": (95, 96, 97),
}

# The decisions this module owns, in the order the season runs.
FIELDS: tuple[str, ...] = tuple(FIELD_ROWS)

# Where a field falls back to when nothing is chosen.
INERT: dict[str, str] = {
    field: (STANDARD_HARVEST if field == "harvest_option" else NONE)
    for field in FIELD_ROWS
}

# Readable names, by Calcs row. The workbook's own abbreviation stays reachable
# as an alias, so nothing here can strand a plan that used it.
#
# B.all is whole-paddock burning, not baling: the workbook rates it 60% in
# cereals and 45% elsewhere with the note "Highly variable. Much lower for
# canola and legumes than cereals", which is the user guide's whole-paddock
# burning row. HSD is the Harrington Seed Destructor and BDS the Bale Direct
# System, both named in the +Prices machinery costs.
DISPLAY_NAMES: dict[int, str] = {
    55: "Glyphosate",
    56: "Paraquat",
    57: "Double knock-down",
    58: "Trifluralin + triallate",
    59: "Propyzamide",
    60: "Sakura",
    61: "Boxer Gold",
    62: "Triazine",
    71: "Topik",
    72: "Hussar",
    73: "Clethodim",
    74: "Glyphosate",
    75: "Paraquat",
    78: "Brown manuring",
    79: "Crop topping",
    81: "Mowing + spray",
    82: "Green manuring",
    83: "Hay + spray",
    84: "Silage + spray",
    85: "Custom spring option 1",
    86: "Custom spring option 2",
    87: "Swathe only",
    88: "Swathe + spray",
    89: "Chaff cart + burn dumps",
    90: "Narrow windrow burn",
    91: "Harrington Seed Destructor",
    92: "Chaff tramlining",
    94: "Bale Direct System",
    95: "Whole paddock burn",
    96: "Custom harvest option 1",
    97: "Custom harvest option 2",
}

# Names earlier versions of this app used, by Calcs row. Kept so a plan saved
# against any of them still resolves.
LEGACY_NAMES: dict[int, tuple[str, ...]] = {
    55: ("Single knock-down",),
    57: ("DoubleK",),
    58: ("Triflur+Triallate", "Triflur+Tria"),
    78: ("Brown man.",),
    79: ("Topping",),
    81: ("Mowing",),
    82: ("Green man.",),
    83: ("Hay & Silage", "Hay"),
    84: ("Silage",),
    87: ("Swathing",),
    89: ("Chaff cart+dumps",),
    91: ("HSD",),
    92: ("Chaff-tramlining", "Tramline"),
    94: ("BDS",),
    95: ("Burn",),
}

# Group prefixes the survival table puts on its labels. Stripping one leaves the
# workbook's own short name for the option.
_PREFIXES = (
    "KD/DK: ", "Pre-E: ", "Post-E: ", "Spring - swathe: ",
    "Spring A1: ", "Spring A2: ", "Spring: ",
    "Harvest B1: ", "Harvest B2: ", "Harvest: ",
)


@dataclass(frozen=True)
class ControlOption:
    """One row of the workbook's option list, control and cost together."""

    row: int                      # Calcs survival row; cost sits at row + 50
    name: str                     # "Sakura", "Silage + spray"
    workbook_name: str            # "Sakura", "Sil.+Spray"
    workbook_label: str           # "Pre-E: Sakura"
    control: dict[int, float]     # crop code -> proportion of ryegrass killed
    cost: dict[int, float]        # crop code -> $/ha

    def works_on(self, crop_code: int) -> bool:
        """Does this do anything at all to ryegrass in this crop?"""
        return self.control.get(crop_code, 0.0) > 0.0

    def cost_in(self, crop_code: int) -> float:
        return self.cost.get(crop_code, 0.0)

    @property
    def crops_it_works_on(self) -> tuple[int, ...]:
        return tuple(code for code, v in sorted(self.control.items()) if v > 0.0)

    @property
    def aliases(self) -> tuple[str, ...]:
        """Every name this option answers to, current and historical."""
        return tuple(dict.fromkeys(
            (self.name, self.workbook_name, self.workbook_label)
            + LEGACY_NAMES.get(self.row, ())
        ))


def _load(path: Path) -> dict:
    if not path.is_file():
        raise FileNotFoundError(
            f"{path} is missing. Regenerate it with:\n"
            r"    .venv\Scripts\python -m tools.extract_params"
        )
    return json.loads(path.read_text(encoding="utf-8"))


def _strip_prefix(label: str) -> str:
    for prefix in _PREFIXES:
        if label.startswith(prefix):
            return label[len(prefix):].strip()
    return label.strip()


@lru_cache(maxsize=1)
def _rows() -> dict[int, ControlOption]:
    """Every row named in :data:`FIELD_ROWS`, control joined to cost."""
    survival = _load(SURVIVAL_PATH)["options"]
    costs = _load(COST_PATH)["options"]

    wanted = sorted({row for rows in FIELD_ROWS.values() for row in rows})
    out: dict[int, ControlOption] = {}
    for row in wanted:
        entry = survival[str(row)]
        # A row with no cost row is free, not missing: the workbook leaves the
        # cell blank where an option carries no cost of its own.
        cost_entry = costs.get(str(row + COST_ROW_OFFSET), {})
        workbook_name = _strip_prefix(entry["label"])
        out[row] = ControlOption(
            row=row,
            name=DISPLAY_NAMES.get(row, workbook_name),
            workbook_name=workbook_name,
            workbook_label=entry["label"],
            control={int(c): float(v) for c, v in entry["by_crop_code"].items()},
            cost={int(c): float(v)
                  for c, v in cost_entry.get("cost_by_crop_code", {}).items()},
        )
    return out


@lru_cache(maxsize=None)
def options_for(field: str) -> tuple[ControlOption, ...]:
    """The options this decision can hold, in the workbook's order."""
    rows = _rows()
    return tuple(rows[row] for row in FIELD_ROWS[field])


def _key(name: object) -> str:
    """Fold a name for lookup: case and inner spacing do not distinguish."""
    return " ".join(str(name).split()).casefold()


@lru_cache(maxsize=None)
def _index(field: str) -> dict[str, ControlOption]:
    """Every name each option answers to, folded.

    Display names are indexed first so that one option's current name always
    beats another option's historical alias.
    """
    index: dict[str, ControlOption] = {}
    for option in options_for(field):
        index.setdefault(_key(option.name), option)
    for option in options_for(field):
        for alias in option.aliases:
            index.setdefault(_key(alias), option)
    return index


def names(field: str) -> list[str]:
    """The dropdown for this decision: doing nothing, then the workbook's list."""
    return [INERT[field]] + [option.name for option in options_for(field)]


def find(field: str, name: object) -> ControlOption | None:
    """The named option for this decision, or None.

    None covers not choosing, a blank, and a name this build does not know -- a
    plan written by a later version, say. Callers treat None as "not done",
    which degrades safely rather than raising.
    """
    if field not in FIELD_ROWS or name in (None, "", INERT[field]):
        return None
    return _index(field).get(_key(name))


def control(field: str, name: object, crop_code: int) -> float:
    """Proportion of germinated ryegrass this choice kills in this crop."""
    option = find(field, name)
    return 0.0 if option is None else option.control.get(crop_code, 0.0)


def cost(field: str, name: object, crop_code: int) -> float:
    """$/ha this choice costs in this crop, from Calcs!N105:T147."""
    option = find(field, name)
    return 0.0 if option is None else option.cost_in(crop_code)


def works_on(field: str, name: object, crop_code: int) -> bool:
    """Would this choice have any effect on ryegrass in this crop?"""
    return control(field, name, crop_code) > 0.0


def row_of(field: str, name: object) -> int | None:
    """The Calcs row this choice is, or None if nothing is chosen.

    Behaviour that depends on *which* option was picked should branch on this
    rather than on the name. A row number is what the workbook actually keys
    on, and it survives every rename.
    """
    option = find(field, name)
    return None if option is None else option.row


def canonical(field: str, name: object) -> str:
    """The current display name for whatever this choice used to be called.

    Resolves the workbook's abbreviation and every historical app name onto the
    name the dropdown shows now, so a plan saved against an older vocabulary
    still selects. Anything unrecognised comes back as the field's inert value
    rather than a name no dropdown offers.
    """
    option = find(field, name)
    return INERT[field] if option is None else option.name


def usable_names(field: str, crop_code: int) -> list[str]:
    """The dropdown narrowed to choices that do something in this crop."""
    return [INERT[field]] + [
        option.name for option in options_for(field) if option.works_on(crop_code)
    ]


def total_cost(decision: dict, crop_code: int) -> float:
    """What this year's weed-control decisions cost, $/ha.

    Every decision this module owns, priced from the workbook's own table. Each
    filled post-emergent slot is its own application and its own cost.
    """
    return sum(cost(field, decision.get(field), crop_code) for field in FIELDS)
