"""Every weed-control decision RIM offers, with what it does and what it costs.

``Calcs`` rows 55-97 and 105-147 are the same list of options twice: once for
what each does to ryegrass, once for what it costs, paired at ``r + 50``. Both
are indexed by crop, because both depend on the crop -- Topik is a
grass-selective cereal herbicide, so it takes 90% of the ryegrass in wheat and
nothing at all in canola, and Glyphosate costs $26/ha in a crop and $22/ha in a
pasture.

This module is the one place that knows which rows belong to which decision on
``2.Strategy``. Both tables are already generated by ``tools/extract_params.py``
into ``data/calcs_survival_table.json`` and ``data/calcs_cost_table.json``;
nothing here is typed.

    knockdown        rows 55-57    2.Strategy row 7
    pre_emergent     rows 58-62    2.Strategy row 8
    post_emergent_1  rows 71-75    2.Strategy row 11
    post_emergent_2  rows 71-75    2.Strategy row 12
    post_emergent_3  rows 71-75    2.Strategy row 13
    spring_option    rows 78-84    2.Strategy row 15
    spring_swathe    rows 87-88    2.Strategy row 16
    spring_others    rows 85-86    2.Strategy row 17
    harvest_option   rows 89-94    2.Strategy row 18
    harvest_others   rows 95-97    2.Strategy row 19

**Names are readable; the workbook's are kept as aliases.** A spreadsheet
abbreviates because a cell is narrow -- "B.all", "Sil.+Spray", "Triflur+Tria" --
and there is no reason to inflict that on a web page. Each row carries a display
name, the workbook label it came from, and every name earlier versions of this
app used. :func:`find` accepts any of them, so renaming a display name can never
strand a saved plan; that is what the alias list is for.

**A zero control is a statement, not a gap.** Where the survival table holds 0
for a crop the option does nothing there, and the workbook means it.
``utils/applicability.py`` reads that and stops offering the option, rather than
charging for something inert.

**The cost table's columns are not in a fixed order.** Rows carry one of two
signatures, ``NOPQRST`` or ``NOPQRTS``, differing in where Clover and Cadiz sit.
The generated file records each row's own signature and has already resolved it
into ``cost_by_crop_code``, so nothing downstream has to know. See
``tools/extract_params.py``.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Mapping, Optional

# A user's own option definitions, as {field: [spec, ...]} -- see
# rim/custom_options.py. A field present replaces that decision's whole list;
# None means "the workbook's values, unchanged".
Custom = Optional[Mapping[str, list]]

_DATA = Path(__file__).resolve().parents[1] / "data"
SURVIVAL_PATH = _DATA / "calcs_survival_table.json"
COST_PATH = _DATA / "calcs_cost_table.json"

# The workbook prices an option's cost row 50 below its control row.
COST_ROW_OFFSET = 50

# The rows RIM leaves for a user to define -- 1.Profile C32:C35. These are the
# only ones a loaded pack displaces; every other option on the same decision is
# a real RIM operation and stays. Whole paddock burn (row 95) sits on
# harvest_others beside the two placeholders, and must survive.
DEFINABLE_ROWS: dict[str, tuple[int, ...]] = {
    "spring_others": (85, 86),
    "harvest_others": (96, 97),
}

# Ids for options a user defined, which have no Calcs row behind them. Kept
# clear of the workbook's 55-97 so nothing that branches on a row -- see
# `row_of` and its callers in rim/ryegrass.py, rim/economics.py and
# rim/yields.py -- can ever match one by accident.
CUSTOM_ROW_BASE = 10_000

# What "this decision was not taken" reads as in a strategy row. Harvest is the
# exception: the paddock is always harvested, just without seed control.
NONE = "None"
STANDARD_HARVEST = "Standard"

# 2.Strategy decision -> the Calcs rows it can hold, in the workbook's order.
FIELD_ROWS: dict[str, tuple[int, ...]] = {
    "knockdown": (55, 56, 57),
    "pre_emergent": (58, 59, 60, 61, 62),
    "post_emergent_1": (71, 72, 73, 74, 75),
    "post_emergent_2": (71, 72, 73, 74, 75),
    "post_emergent_3": (71, 72, 73, 74, 75),
    # 2.Strategy D91:D96 order: Green M., Brown M, Mow+Spray, Sil.+Spray,
    # Hay+Spray, Topping.
    "spring_option": (82, 78, 81, 84, 83, 79),
    "spring_swathe": (87, 88),
    "spring_others": (85, 86),
    # D108:D112 order: Cart+B., Narr+B., HSD, Tram., BDS+E. Row 93 is the
    # workbook's spare slot and is not offered.
    "harvest_option": (89, 90, 91, 92, 94),
    "harvest_others": (95, 96, 97),
}

# The decisions this module owns, in the order the season runs.
FIELDS: tuple[str, ...] = tuple(FIELD_ROWS)

# Where a field falls back to when nothing is chosen.
INERT: dict[str, str] = {
    field: (STANDARD_HARVEST if field == "harvest_option" else NONE)
    for field in FIELD_ROWS
}

# Readable names, by Calcs row. The workbook's own abbreviation stays reachable
# as an alias, so nothing here can strand a plan that used it.
#
# B.all is whole-paddock burning, not baling: the workbook rates it 60% in
# cereals and 45% elsewhere with the note "Highly variable. Much lower for
# canola and legumes than cereals", which is the user guide's whole-paddock
# burning row. HSD is the Harrington Seed Destructor and BDS the Bale Direct
# System, both named in the +Prices machinery costs.
DISPLAY_NAMES: dict[int, str] = {
    55: "Glyphosate",
    56: "Paraquat",
    57: "Double knock-down",
    58: "Trifluralin + triallate",
    59: "Propyzamide",
    60: "Sakura",
    61: "Boxer Gold",
    62: "Triazine",
    71: "Topik",
    72: "Hussar",
    73: "Clethodim",
    74: "Glyphosate",
    75: "Paraquat",
    78: "Brown manuring",
    79: "Crop topping",
    81: "Mowing + spray",
    82: "Green manuring",
    83: "Hay + spray",
    84: "Silage + spray",
    85: "Custom spring option 1",
    86: "Custom spring option 2",
    87: "Swathe only",
    88: "Swathe + spray",
    89: "Chaff cart + burn dumps",
    90: "Narrow windrow burn",
    91: "Harrington Seed Destructor",
    92: "Chaff tramlining",
    94: "Bale Direct System",
    95: "Whole paddock burn",
    96: "Custom harvest option 1",
    97: "Custom harvest option 2",
}

# Names earlier versions of this app used, by Calcs row. Kept so a plan saved
# against any of them still resolves.
LEGACY_NAMES: dict[int, tuple[str, ...]] = {
    55: ("Single knock-down",),
    57: ("DoubleK",),
    58: ("Triflur+Triallate", "Triflur+Tria"),
    78: ("Brown man.",),
    79: ("Topping",),
    81: ("Mowing",),
    82: ("Green man.",),
    83: ("Hay & Silage", "Hay"),
    84: ("Silage",),
    87: ("Swathing",),
    89: ("Chaff cart+dumps",),
    91: ("HSD",),
    92: ("Chaff-tramlining", "Tramline"),
    94: ("BDS",),
    95: ("Burn",),
}

# Group prefixes the survival table puts on its labels. Stripping one leaves the
# workbook's own short name for the option.
_PREFIXES = (
    "KD/DK: ", "Pre-E: ", "Post-E: ", "Spring - swathe: ",
    "Spring A1: ", "Spring A2: ", "Spring: ",
    "Harvest B1: ", "Harvest B2: ", "Harvest: ",
)


@dataclass(frozen=True)
class ControlOption:
    """One row of the workbook's option list, control and cost together."""

    row: int                      # Calcs survival row; cost sits at row + 50
    name: str                     # "Sakura", "Silage + spray"
    workbook_name: str            # "Sakura", "Sil.+Spray"
    workbook_label: str           # "Pre-E: Sakura"
    control: dict[int, float]     # crop code -> proportion of ryegrass killed
    cost: dict[int, float]        # crop code -> $/ha
    extra_aliases: tuple[str, ...] = ()   # names inherited from a row it replaces

    def works_on(self, crop_code: int) -> bool:
        """Does this do anything at all to ryegrass in this crop?"""
        return self.control.get(crop_code, 0.0) > 0.0

    def cost_in(self, crop_code: int) -> float:
        return self.cost.get(crop_code, 0.0)

    @property
    def crops_it_works_on(self) -> tuple[int, ...]:
        return tuple(code for code, v in sorted(self.control.items()) if v > 0.0)

    @property
    def aliases(self) -> tuple[str, ...]:
        """Every name this option answers to, current and historical.

        A user-renamed slot keeps its default name here too, so a plan written
        before the rename still selects the right row.
        """
        return tuple(dict.fromkeys(
            (self.name, DISPLAY_NAMES.get(self.row, self.workbook_name),
             self.workbook_name, self.workbook_label)
            + LEGACY_NAMES.get(self.row, ())
            + self.extra_aliases
        ))


def _load(path: Path) -> dict:
    if not path.is_file():
        raise FileNotFoundError(
            f"{path} is missing. Regenerate it with:\n"
            r"    .venv\Scripts\python -m tools.extract_params"
        )
    return json.loads(path.read_text(encoding="utf-8"))


def _strip_prefix(label: str) -> str:
    for prefix in _PREFIXES:
        if label.startswith(prefix):
            return label[len(prefix):].strip()
    return label.strip()


@lru_cache(maxsize=1)
def _rows() -> dict[int, ControlOption]:
    """Every row named in :data:`FIELD_ROWS`, control joined to cost."""
    survival = _load(SURVIVAL_PATH)["options"]
    costs = _load(COST_PATH)["options"]

    wanted = sorted({row for rows in FIELD_ROWS.values() for row in rows})
    out: dict[int, ControlOption] = {}
    for row in wanted:
        entry = survival[str(row)]
        # A row with no cost row is free, not missing: the workbook leaves the
        # cell blank where an option carries no cost of its own.
        cost_entry = costs.get(str(row + COST_ROW_OFFSET), {})
        workbook_name = _strip_prefix(entry["label"])
        out[row] = ControlOption(
            row=row,
            name=DISPLAY_NAMES.get(row, workbook_name),
            workbook_name=workbook_name,
            workbook_label=entry["label"],
            control={int(c): float(v) for c, v in entry["by_crop_code"].items()},
            cost={int(c): float(v)
                  for c, v in cost_entry.get("cost_by_crop_code", {}).items()},
        )
    return out


@lru_cache(maxsize=None)
def _workbook_options_for(field: str) -> tuple[ControlOption, ...]:
    rows = _rows()
    return tuple(rows[row] for row in FIELD_ROWS[field])


def options_for(field: str, custom: Custom = None) -> tuple[ControlOption, ...]:
    """The options this decision can hold, in order.

    ``custom`` holds a user's own definitions -- see :mod:`rim.custom_options`.
    Where it names this decision, the user's options displace RIM's placeholder
    slots for it -- those were only ever stand-ins for exactly this, so once a
    user has defined their own the stand-ins are noise. Everything else on that
    decision stays: whole-paddock burning is a real RIM operation that happens
    to sit beside the two harvest placeholders, not one of them.

    It is passed in rather than held here because one Streamlit server serves
    many browsers, and one user's options must not appear in another's session.
    """
    specs = (custom or {}).get(field)
    if not specs:
        return _workbook_options_for(field)

    displaced = DEFINABLE_ROWS.get(field, ())
    kept = tuple(option for option in _workbook_options_for(field)
                 if option.row not in displaced)
    return kept + tuple(_defined(field, position, spec)
                        for position, spec in enumerate(specs))


def _defined(field: str, position: int, spec: Mapping) -> ControlOption:
    """One option a user defined, with an id of its own rather than a Calcs row.

    ``spec["replaces"]`` names a placeholder row this option stands in for, and
    only the keyed form of the file sets it -- there ``spring_1`` *is* row 85, so
    a plan that said "Custom spring option 1" should keep working after it is
    renamed. A list of options carries no such mapping and gets no alias: which
    of five new options a placeholder became is not something to guess at, and
    the gate reports the stale choice instead.
    """
    name = str(spec["name"]).strip()
    replaced = spec.get("replaces")
    inherited: tuple[str, ...] = ()
    if replaced is not None:
        stand_in = _rows().get(int(replaced))
        if stand_in is not None:
            inherited = stand_in.aliases

    return ControlOption(
        row=CUSTOM_ROW_BASE + FIELDS.index(field) * 1_000 + position,
        name=name,
        workbook_name=name,
        workbook_label=name,
        control=dict(spec["control"]),
        cost=dict(spec["cost"]),
        extra_aliases=inherited,
    )


def _key(name: object) -> str:
    """Fold a name for lookup: case and inner spacing do not distinguish."""
    return " ".join(str(name).split()).casefold()


def _index(field: str, custom: Custom = None) -> dict[str, ControlOption]:
    """Every name each option answers to, folded.

    Display names are indexed first so that one option's current name always
    beats another option's historical alias. A renamed custom slot keeps its
    workbook name as an alias too, so a plan that used the old name still
    resolves.
    """
    index: dict[str, ControlOption] = {}
    options = options_for(field, custom)
    for option in options:
        index.setdefault(_key(option.name), option)
    for option in options:
        for alias in option.aliases:
            index.setdefault(_key(alias), option)
    return index


def names(field: str, custom: Custom = None) -> list[str]:
    """The dropdown for this decision: doing nothing, then the list."""
    return [INERT[field]] + [o.name for o in options_for(field, custom)]


def find(field: str, name: object, custom: Custom = None) -> ControlOption | None:
    """The named option for this decision, or None.

    None covers not choosing, a blank, and a name this build does not know -- a
    plan written by a later version, say. Callers treat None as "not done",
    which degrades safely rather than raising.
    """
    if field not in FIELD_ROWS or name in (None, "", INERT[field]):
        return None
    return _index(field, custom).get(_key(name))


def control(field: str, name: object, crop_code: int, custom: Custom = None) -> float:
    """Proportion of germinated ryegrass this choice kills in this crop."""
    option = find(field, name, custom)
    return 0.0 if option is None else option.control.get(crop_code, 0.0)


def cost(field: str, name: object, crop_code: int, custom: Custom = None) -> float:
    """$/ha this choice costs in this crop, from Calcs!N105:T147."""
    option = find(field, name, custom)
    return 0.0 if option is None else option.cost_in(crop_code)


def works_on(field: str, name: object, crop_code: int, custom: Custom = None) -> bool:
    """Would this choice have any effect on ryegrass in this crop?"""
    return control(field, name, crop_code, custom) > 0.0


def row_of(field: str, name: object, custom: Custom = None) -> int | None:
    """The Calcs row this choice is, or None if nothing is chosen.

    Behaviour that depends on *which* option was picked should branch on this
    rather than on the name. A row number is what the workbook actually keys
    on, and it survives every rename.
    """
    option = find(field, name, custom)
    return None if option is None else option.row


def canonical(field: str, name: object, custom: Custom = None) -> str:
    """The current display name for whatever this choice used to be called.

    Resolves the workbook's abbreviation and every historical app name onto the
    name the dropdown shows now, so a plan saved against an older vocabulary
    still selects. Anything unrecognised comes back as the field's inert value
    rather than a name no dropdown offers.
    """
    option = find(field, name, custom)
    return INERT[field] if option is None else option.name


def usable_names(field: str, crop_code: int, custom: Custom = None) -> list[str]:
    """The dropdown narrowed to choices that do something in this crop."""
    return [INERT[field]] + [
        o.name for o in options_for(field, custom) if o.works_on(crop_code)
    ]


def total_cost(decision: dict, crop_code: int, custom: Custom = None) -> float:
    """What this year's weed-control decisions cost, $/ha.

    Every decision this module owns, priced from the workbook's own table. Each
    filled post-emergent slot is its own application and its own cost.
    """
    return sum(cost(field, decision.get(field), crop_code, custom)
               for field in FIELDS)


def custom_from(options: Mapping | None) -> Custom:
    """A user's own option definitions, out of the options bundle.

    Stored under ``custom_options`` so it saves with the scenario and reaches
    the engine as a parameter like any other.

    JSON has no integer keys. A round trip through a save file turns the crop
    codes into strings, and a crop code that arrives as ``"0"`` never matches a
    lookup by ``0`` -- the option silently reads as controlling nothing and
    costing nothing. So they are put back here, in the one place every reader
    passes through.
    """
    if not options:
        return None
    raw = options.get("custom_options")
    if not raw:
        return None

    out: dict[str, list[dict]] = {}
    for field, specs in raw.items():
        restored = []
        for spec in specs:
            entry = dict(spec)
            for key in ("control", "cost"):
                if isinstance(entry.get(key), Mapping):
                    entry[key] = {int(code): float(value)
                                  for code, value in entry[key].items()}
            restored.append(entry)
        if restored:
            out[str(field)] = restored
    return out or None
