"""Every weed-control decision RIM offers, with what it does and what it costs.

``Calcs`` rows 55-97 and 105-147 are the same list of options twice: once for
what each does to ryegrass, once for what it costs, paired at ``r + 50``. Both
are indexed by crop, because both depend on the crop -- Topik is a
grass-selective cereal herbicide, so it takes 90% of the ryegrass in wheat and
nothing at all in canola, and Glyphosate costs $26/ha in a crop and $22/ha in a
pasture.

This module is the one place that knows which rows belong to which decision on
``2.Strategy``. Both tables are already generated by ``tools/extract_params.py``
into ``data/calcs_survival_table.json`` and ``data/calcs_cost_table.json``;
nothing here is typed.

    knockdown        rows 55-57    2.Strategy row 7
    pre_emergent     rows 58-62    2.Strategy row 8
    post_emergent_1  rows 71-75    2.Strategy row 11
    post_emergent_2  rows 71-75    2.Strategy row 12
    post_emergent_3  rows 71-75    2.Strategy row 13
    spring_option    rows 78-84    2.Strategy row 15
    spring_swathe    rows 87-88    2.Strategy row 16
    spring_others    rows 85-86    2.Strategy row 17
    harvest_option   rows 89-94    2.Strategy row 18
    harvest_others   rows 95-97    2.Strategy row 19

**Names are the workbook's own.** They are the labels a RIM user already reads
in ``1.Profile`` and in the ``2.Strategy`` dropdowns, so "Sil.+Spray" stays
"Sil.+Spray" rather than becoming something tidier that matches no source.

**A zero control is a statement, not a gap.** Where the survival table holds 0
for a crop the option does nothing there, and the workbook means it.
``utils/applicability.py`` reads that and stops offering the option, rather than
charging for something inert.

**The cost table's columns are not in a fixed order.** Rows carry one of two
signatures, ``NOPQRST`` or ``NOPQRTS``, differing in where Clover and Cadiz sit.
The generated file records each row's own signature and has already resolved it
into ``cost_by_crop_code``, so nothing downstream has to know. See
``tools/extract_params.py``.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

_DATA = Path(__file__).resolve().parents[1] / "data"
SURVIVAL_PATH = _DATA / "calcs_survival_table.json"
COST_PATH = _DATA / "calcs_cost_table.json"

# The workbook prices an option's cost row 50 below its control row.
COST_ROW_OFFSET = 50

# What "this decision was not taken" reads as in a strategy row. Harvest is the
# exception: the paddock is always harvested, just without seed control.
NONE = "None"
STANDARD_HARVEST = "Standard"

# 2.Strategy decision -> the Calcs rows it can hold, in the workbook's order.
FIELD_ROWS: dict[str, tuple[int, ...]] = {
    "knockdown": (55, 56, 57),
    "pre_emergent": (58, 59, 60, 61, 62),
    "post_emergent_1": (71, 72, 73, 74, 75),
    "post_emergent_2": (71, 72, 73, 74, 75),
    "post_emergent_3": (71, 72, 73, 74, 75),
    # 2.Strategy D91:D96 order: Green M., Brown M, Mow+Spray, Sil.+Spray,
    # Hay+Spray, Topping.
    "spring_option": (82, 78, 81, 84, 83, 79),
    "spring_swathe": (87, 88),
    "spring_others": (85, 86),
    # D108:D112 order: Cart+B., Narr+B., HSD, Tram., BDS+E. Row 93 is the
    # workbook's spare slot and is not offered.
    "harvest_option": (89, 90, 91, 92, 94),
    "harvest_others": (95, 96, 97),
}

# The decisions this module owns, in the order the season runs.
FIELDS: tuple[str, ...] = tuple(FIELD_ROWS)

# Where a field falls back to when nothing is chosen.
INERT: dict[str, str] = {
    field: (STANDARD_HARVEST if field == "harvest_option" else NONE)
    for field in FIELD_ROWS
}

# Group prefixes the survival table puts on its labels. Stripping one leaves the
# name the option is actually known by.
_PREFIXES = (
    "KD/DK: ", "Pre-E: ", "Post-E: ", "Spring - swathe: ",
    "Spring A1: ", "Spring A2: ", "Spring: ",
    "Harvest B1: ", "Harvest B2: ", "Harvest: ",
)


@dataclass(frozen=True)
class ControlOption:
    """One row of the workbook's option list, control and cost together."""

    row: int                      # Calcs survival row; cost sits at row + 50
    name: str                     # "Sakura", "Sil.+Spray"
    workbook_label: str           # "Pre-E: Sakura"
    control: dict[int, float]     # crop code -> proportion of ryegrass killed
    cost: dict[int, float]        # crop code -> $/ha

    def works_on(self, crop_code: int) -> bool:
        """Does this do anything at all to ryegrass in this crop?"""
        return self.control.get(crop_code, 0.0) > 0.0

    def cost_in(self, crop_code: int) -> float:
        return self.cost.get(crop_code, 0.0)

    @property
    def crops_it_works_on(self) -> tuple[int, ...]:
        return tuple(code for code, v in sorted(self.control.items()) if v > 0.0)


def _load(path: Path) -> dict:
    if not path.is_file():
        raise FileNotFoundError(
            f"{path} is missing. Regenerate it with:\n"
            r"    .venv\Scripts\python -m tools.extract_params"
        )
    return json.loads(path.read_text(encoding="utf-8"))


def _strip_prefix(label: str) -> str:
    for prefix in _PREFIXES:
        if label.startswith(prefix):
            return label[len(prefix):].strip()
    return label.strip()


@lru_cache(maxsize=1)
def _rows() -> dict[int, ControlOption]:
    """Every row named in :data:`FIELD_ROWS`, control joined to cost."""
    survival = _load(SURVIVAL_PATH)["options"]
    costs = _load(COST_PATH)["options"]

    wanted = sorted({row for rows in FIELD_ROWS.values() for row in rows})
    out: dict[int, ControlOption] = {}
    for row in wanted:
        entry = survival[str(row)]
        # A row with no cost row is free, not missing: the workbook leaves the
        # cell blank where an option carries no cost of its own.
        cost_entry = costs.get(str(row + COST_ROW_OFFSET), {})
        out[row] = ControlOption(
            row=row,
            name=_strip_prefix(entry["label"]),
            workbook_label=entry["label"],
            control={int(c): float(v) for c, v in entry["by_crop_code"].items()},
            cost={int(c): float(v)
                  for c, v in cost_entry.get("cost_by_crop_code", {}).items()},
        )
    return out


@lru_cache(maxsize=None)
def options_for(field: str) -> tuple[ControlOption, ...]:
    """The options this decision can hold, in the workbook's order."""
    rows = _rows()
    return tuple(rows[row] for row in FIELD_ROWS[field])


@lru_cache(maxsize=None)
def _index(field: str) -> dict[str, ControlOption]:
    return {option.name: option for option in options_for(field)}


def names(field: str) -> list[str]:
    """The dropdown for this decision: doing nothing, then the workbook's list."""
    return [INERT[field]] + [option.name for option in options_for(field)]


def find(field: str, name: object) -> ControlOption | None:
    """The named option for this decision, or None.

    None covers not choosing, a blank, and a name this build does not know -- a
    plan written by a later version, say. Callers treat None as "not done",
    which degrades safely rather than raising.
    """
    if field not in FIELD_ROWS or name in (None, "", INERT[field]):
        return None
    return _index(field).get(str(name).strip())


def control(field: str, name: object, crop_code: int) -> float:
    """Proportion of germinated ryegrass this choice kills in this crop."""
    option = find(field, name)
    return 0.0 if option is None else option.control.get(crop_code, 0.0)


def cost(field: str, name: object, crop_code: int) -> float:
    """$/ha this choice costs in this crop, from Calcs!N105:T147."""
    option = find(field, name)
    return 0.0 if option is None else option.cost_in(crop_code)


def works_on(field: str, name: object, crop_code: int) -> bool:
    """Would this choice have any effect on ryegrass in this crop?"""
    return control(field, name, crop_code) > 0.0


def usable_names(field: str, crop_code: int) -> list[str]:
    """The dropdown narrowed to choices that do something in this crop."""
    return [INERT[field]] + [
        option.name for option in options_for(field) if option.works_on(crop_code)
    ]


def total_cost(decision: dict, crop_code: int) -> float:
    """What this year's weed-control decisions cost, $/ha.

    Every decision this module owns, priced from the workbook's own table. Each
    filled post-emergent slot is its own application and its own cost.
    """
    return sum(cost(field, decision.get(field), crop_code) for field in FIELDS)
