from __future__ import annotations

import streamlit as st

from utils.theme import inject_uwa_theme, uwa_page_header, uwa_footer, uwa_sidebar_logo


inject_uwa_theme()
uwa_sidebar_logo()

uwa_page_header(
    title="Credits & Information",
    subtitle="About RIM Online and the University of Western Australia",
    icon="🎓",
)

col_l, col_r = st.columns([3, 2])

with col_l:
    st.markdown("### About RIM Online")
    st.write(
        "Ryegrass Integrated Management (RIM) is a whole-farm bioeconomic simulation tool "
        "designed for integrated weed management analysis. It models the long-term interaction "
        "between annual ryegrass (*Lolium rigidum*) population dynamics and management decisions "
        "across a typical crop rotation."
    )

    st.markdown("### Acknowledgements")
    st.markdown(
        """
        <div class="uwa-section-card">
          <ul style="margin:0;padding-left:1.2rem;line-height:2;">
            <li><strong>The University of Western Australia (UWA)</strong></li>
            <li>Department of Agriculture and Food Western Australia (historical)</li>
            <li>Grains Research and Development Corporation (GRDC)</li>
            <li>Australian Herbicide Resistance Initiative (AHRI)</li>
          </ul>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown("### Citation Guidance")
    st.write(
        "Please refer to the original RIM model documentation and associated peer-reviewed "
        "publications when citing results generated by this tool. Contact UWA for the most "
        "current citation details."
    )

    st.markdown("### Notes for This Web App")
    st.info(
        "This Streamlit implementation is a Python translation of the VBA-based Excel workflow. "
        "It is designed for iterative model calibration against the Excel baseline. "
        "Model formula calibration and parameter validation are ongoing."
    )

with col_r:
    st.markdown(
        f"""
        <div style="
          background:var(--uwa-navy);
          border-radius:12px;
          padding:2rem;
          text-align:center;
          color:#fff;
          box-shadow:0 4px 18px rgba(0,48,135,0.25);">
          <div style="font-size:3rem;line-height:1;margin-bottom:0.6rem;">🎓</div>
          <div style="
            font-size:1.25rem;
            font-weight:800;
            letter-spacing:-0.01em;
            margin-bottom:0.3rem;">University of Western Australia</div>
          <div style="
            font-size:0.82rem;
            color:rgba(255,255,255,0.7);
            margin-bottom:1.2rem;">Perth, Western Australia</div>
          <div style="
            display:inline-block;
            background:#DAAA00;
            color:#003087;
            font-weight:700;
            font-size:0.8rem;
            padding:0.3rem 1rem;
            border-radius:999px;
            text-transform:uppercase;
            letter-spacing:0.06em;">Established 1911</div>
          <hr style="border-color:rgba(255,255,255,0.2);margin:1.2rem 0;">
          <a href="https://www.uwa.edu.au" target="_blank"
             style="color:#DAAA00;font-weight:600;font-size:0.88rem;text-decoration:none;">
            www.uwa.edu.au →
          </a>
        </div>
        """,
        unsafe_allow_html=True,
    )
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown("### Contact")
    st.write("For model queries or collaboration, contact the relevant research team at UWA.")

uwa_footer()
